name: Send Push Notifications

on:
  schedule:
    # テスト用: 12:15 JST = 3:15 UTC（毎日）
    - cron: '15 3 * * *'
    # 本番用: 18:00-24:00 JST = 9:00-15:00 UTC（1時間ごと）
    # - cron: '0 9-15 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  send-notifications:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd server && npm install

      - name: Send notifications
        run: cd server && npm run send-notifications
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          VAPID_PUBLIC_KEY: ${{ secrets.VAPID_PUBLIC_KEY }}
          VAPID_PRIVATE_KEY: ${{ secrets.VAPID_PRIVATE_KEY }}
          VAPID_SUBJECT: ${{ secrets.VAPID_SUBJECT }}
